-- Add Unique constraint to users' email
CREATE TABLE IF NOT EXISTS order_items
(
    sequence   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   INTEGER                             NOT NULL,
    quantity   INTEGER                                  NOT NULL,
    price      DOUBLE PRECISION,
    product_id INTEGER,
    CONSTRAINT pk_orderitem PRIMARY KEY (sequence, order_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id   INTEGER                NOT NULL,
    user_id    INTEGER                     NOT NULL,
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    total      DOUBLE PRECISION            NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS products
(
    product_id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

-- Alter role type and set it as not nullable
ALTER TABLE users
ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
ALTER COLUMN role TYPE varchar(8);
ALTER TABLE users
ALTER COLUMN role SET NOT NULL;

ALTER TABLE users
ADD CONSTRAINT chk_role_valid CHECK (role IN ('admin', 'customer'));

ALTER TABLE order_items
    ADD CONSTRAINT uc_orderitem_product UNIQUE (product_id);

ALTER TABLE users
    ADD COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDERITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);