ALTER TABLE order_items
    DROP CONSTRAINT pk_orderitem;

ALTER TABLE order_items
    DROP COLUMN sequence;

ALTER TABLE order_items
    ADD COLUMN order_items_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE order_items
    ADD CONSTRAINT pk_orderitems PRIMARY KEY (order_items_id);